# Generated by Django 5.0.4 on 2024-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Book name')),
                ('page_count', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Numer of pages')),
                ('category', models.CharField(max_length=31, verbose_name='Category')),
                ('author_name', models.CharField(max_length=31, verbose_name='Author')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
                ('image', models.ImageField(upload_to='', verbose_name='Load image')),
            ],
        ),
    ]
