# Generated by Django 5.0.4 on 2024-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Numer of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Price'),
        ),
    ]
