# Generated by Django 5.0.4 on 2024-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_author_book_cover_type_remove_book_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('soft', 'Soft'), ('hard', 'Hard'), ('special', 'Special')], max_length=31, null=True, verbose_name='Cover type'),
        ),
    ]
