# Generated by Django 5.0.4 on 2024-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_category_remove_book_author_name_book_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='market.category', verbose_name='Categories'),
        ),
    ]
